federated_search_hub.settings:
  type: config_object
  label: 'Federated Search Hub settings'
  mapping:
    site_labels:
      type: sequence
      label: 'Site labels'
      sequence:
        type: mapping
        label: 'Site label'
        mapping:
          site_id:
            type: string
            label: 'Site ID'
          label:
            type: string
            label: 'Display label'
